### PR TITLE
Added Home, User, Post, Event And Settings Routes

### PR DESCRIPTION
**Pull request by gideon-del**
Done with routes

### CODE REVIEW

**Comment by williamssam** [comment]
Hi @gideon-del, Pls resolve the conflicts

**Comment by gideon-del** [comment]
i have resolved it

**Review by pablo-clueless — CHANGES_REQUESTED** [review]
- Fix the lock file

**Comment by gideon-del** [comment]
Please try it again i have fixed the lock file

**Review by pablo-clueless — APPROVED** [review]

**Pull request merged**
